### ISSUE TITLE
Create file submission page

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/record-cleaner-ui#2]
- [x] Create file upload page
- [x] Submit file to service
- [x] Present results

**Comment by kitenetter** [comment]
@JimBacon you're probably aware of this, but the recently upgraded iRecord spreadsheet importer is [available here](https://irecord.org.uk/import/v2). 

The upgrade has enabled:
- Steps are clearer and better annotated on-screen
- Rarely used options (e.g. for survey to import into, and for attributes to match) are hidden by default, so that users can find the most frequently used options more easily
- Checking of species name matches, and matches to other termlists such as Stage, are carried out and can be corrected as part of the import process
- If other validation errors are encountered (e.g. incorrect formats for date or grid ref) an error file can be downloaded - no records will be imported until the errors are fixed and the file has been re-imported
- Additional metadata about the file being imported can be added (although we haven't yet implemented a way of viewing this metadata after import)

Not sure if any of the development work can be re-used for record cleaner, or if you need to start from scratch.

(I had also mentioned the Pantheon 'scratchpad' process for uploading data, but that only deals with taxon lists, so won't help with dates and locations etc.)

**Comment by JimBacon** [comment]
While there is plenty of scope for improvement, this has been completed in v1.0.0
